version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts-jessie-browsers

    steps:
      - checkout
      - run: npm install
      - run: npm test

  publish:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
      - run:
            name: Publish to NPM
            command: |
              npm install
              npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
              npm run build -- --prod
              cd dist/ng2-brpipes
              npm publish

workflows:
  version: 2
  tagged-build:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
